drop table respuestas;

create table respuestas(
idResuesta integer primary key auto_increment,
respuesta varchar(250),
idPregunta integer,
foreign key (idPregunta) references preguntas(idPregunta));

insert into respuestas( respuesta, idPregunta) values
("MANERA   INDIVIDUAL", 1),
("COLECTIVO", 1),
("EMPRESA", 1),
("Si", 3),
("No", 3),
("  Producciones escénicas, de festivales y representación artística", 5),
("Gestión de espacios culturales", 5),
("Promoción, difusión, extensión y mercadotecnia cultural.", 5),
("Programas de educación artística formal y no formal (talleres)", 5),
("Gestión de galerías de arte y museos", 5),
("Museología, museografía y curaduría", 5),
("Gestión de turismo cultural", 5),
("Visitas guiadas (museos y sitios históricos y de Patrimonio)", 5),
("Recorridos culturales", 5),
("Teatro", 5),
("Circo", 5),
("Escenografía", 5),
("Dramaturgia", 5),
("Clown y mimos", 5),
("Títeres", 5),
("Musicales", 5),
("Performance", 5),
("Narración oral", 5),
("Pintura", 5),
("Grabado", 5),
("Escultura", 5),
("Fotografía", 5),
("Dibujo", 5),
("Arte objeto tradicional y contemporáneo", 5),
("Arquitectura (diseño, producción y conservación)", 5),
("Restauración de bienes muebles.", 5),
("Grafitti", 5),
("Tags", 5),
("Música  (educación y producción)", 5),
("Opera", 5),
("Laudería", 5),
("Arte Sonoro", 5),
("Creación literaria", 5),
("Producción editorial y medios impresos", 5),
("Gestión de bibliotecas y programas de fomento a la lectura", 5),
("Danza Contemporánea", 5),
("Ballet", 5),
("Danza  Folklórica", 5),
("Danza  Indígena", 5),
("Hip-Hop", 5),
("Bailes de Salón", 5),
("Arte huichol", 5),
("Hueso y cuerno", 5),
("Cine y producción audiovisual", 5),
("Televisión", 5),
("Radio", 5),
("Software y programas creativos digitales", 5),
("Animación", 5),
("Diseño gráfico y editorial", 5),
("Diseño de moda y joyería", 5),
(" Diseño  Textil", 5),
("Diseño Digital", 5),
("Si", 6),
("No", 6),
("Si", 9),
("No", 9),
("Si", 11),
("No", 11),
("Años", 13),
("Meses", 13),
("Álvaro Obregón", 17),
("Azcapotzalco", 17),
("Benito Juárez", 17),
("Coyoacán", 17),
("Cuajimalpa", 17),
("Cuauhtémoc", 17),
("Gustavo A. Madero", 17),
("Iztacalco", 17),
("Iztapalapa", 17),
("Magdalena Contreras", 17),
("Miguel Hidalgo", 17),
("Milpa Alta", 17),
("Tláhuac", 17),
("Tlalpan", 17),
("Venustiano Carranza", 17),
("Xochimilco ", 17),
("Álvaro Obregón", 18),
("Azcapotzalco", 18),
("Benito Juárez", 18),
("Coyoacán", 18),
("Cuajimalpa", 18),
("Cuauhtémoc", 18),
("Gustavo A. Madero", 18),
("Iztacalco", 18),
("Iztapalapa", 18),
("Magdalena Contreras", 18),
("Miguel Hidalgo", 18),
("Milpa Alta", 18),
("Tláhuac", 18),
("Tlalpan", 18),
("Venustiano Carranza", 18),
("Xochimilco ", 18),
("Lunes", 19),
("Martes", 19),
("Miercoles", 19),
("Jueves", 19),
("Viernes", 19),
("Sábado", 19),
("Domingo", 19),
("Bueno", 27),
("Regular", 27),
("Malo", 27),
("Si", 30),
("No", 30),
("Si", 32),
("No", 32),
("Si", 39),
("No", 39),
("La tiene por su actividad artístico-cultural", 40),
("Personal la paga por su cuenta", 40),
("Esposo /esposa", 40),
("Familiar", 40),
("Otra especificar", 40),
("Si", 41),
("No", 41),
("Si", 42),
("No", 42),
("Si", 45),
("No", 45),
("Propio", 47),
("Rentado", 47),
("Prestado", 47),
("No tiene", 47),
("Otro", 47),
("Casa", 48),
("Otro espacio", 48),
("Si", 50),
("No", 50),
("Una Fondeadora", 58),
("Financiamiento Privado", 58),
("Banco", 58),
("Familia", 58),
("Mis ahorros", 58),
("Otro 1", 58),
("Otro 2", 58),
("Si", 59),
("No", 59),
("SOLTER@", 72),
("CASAD@", 72),
("UNION LIBRE", 72),
("DIVORCIAD@", 72),
("VIUD@", 72),
("Si", 74),
("No", 74),
("ASPIRADORA", 75),
("TOSTADOR DE PAN", 75),
("BOILER DE GAS", 75),
("ESTUFA DE GAS O ELÉCTRICA", 75),
("Si", 84),
("No", 84),
("NO ESTUDIO", 85),
("PRIMARIA INCOMPLETA ", 85),
("PRIMARIA COMPLETA", 85),
("SECUNDARIA INCOMPLETA", 85),
("SECUNDARIA COMPLETA", 85),
("CARRERA COMERCIAL", 85),
("CARRERA TÉCNICA", 85),
("PREPARATORIA INCOMPLETA", 85),
("PREPARATORIA COMPLETA", 85),
("LICENCIATURA INCOMPLETA", 85),
("LICENCIATURA COMPLETA", 85),
("DIPLOMADO O MAESTRÍA", 85),
("NO ESTUDIO", 86),
("PRIMARIA INCOMPLETA ", 86),
("PRIMARIA COMPLETA", 86),
("SECUNDARIA INCOMPLETA", 86),
("SECUNDARIA COMPLETA", 86),
("CARRERA COMERCIAL", 86),
("CARRERA TÉCNICA", 86),
("PREPARATORIA INCOMPLETA", 86),
("PREPARATORIA COMPLETA", 86),
("LICENCIATURA INCOMPLETA", 86),
("LICENCIATURA COMPLETA", 86),
("DIPLOMADO O MAESTRÍA", 86),
("Álvaro Obregón", 88),
("Azcapotzalco", 88),
("Benito Juárez", 88),
("Coyoacán", 88),
("Cuajimalpa", 88),
("Cuauhtémoc", 88),
("Gustavo A. Madero", 88),
("Iztacalco", 88),
("Iztapalapa", 18),
("Magdalena Contreras", 88),
("Miguel Hidalgo", 88),
("Milpa Alta", 88),
("Tláhuac", 88),
("Tlalpan", 88),
("Venustiano Carranza", 88),
("Xochimilco ", 88);